GET http://localhost:80/api/product

###
GET http://localhost:80/api/product/2

###
POST http://localhost:80/api/product
Content-Type: application/json

{
  "name": "Palow",
  "description": "To'y oshi",
  "price": 25000,
  "photo": "palow.jpg",
  "categoryId": 1
}

###
PUT http://localhost:80/api/product/2
Content-Type: application/json

{
  "name": "T-Shirt",
  "description": "White T-Shirt with three red lines. Consist 90% of cotton ",
  "price": 279000,
  "photo": "t_shirt.jpg",
  "categoryId": 2
}

###
DELETE http://localhost:80/api/product/7